apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: k3s-config
              mountPath: /root/.kube/config
            - name: env-file
              mountPath: /app/.env
            - name: ssh-key
              mountPath: /app/id_rsa.pub
      volumes:
        - name: k3s-config
          hostPath:
            path: /etc/rancher/k3s/k3s.yaml
            type: File
        - name: env-file
          hostPath:
            path: /home/ubuntu/.env
            type: File
        - name: ssh-key
          hostPath:
            path: /home/ubuntu/id_rsa.pub
            type: File
      hostNetwork: true
      nodeSelector:
        node-role.kubernetes.io/master: "true"
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Equal
          value: "true"
          effect: NoSchedule