apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: kubeconfig
              mountPath: /root/.kube/
      volumes:
        - name: kubeconfig
          hostPath:
            path: /root/.kube/
            type: Directory
      nodeSelector:
        master: ""
      tolerations:
        - key: master
          operator: Exists
          effect: NoSchedule